"""add energy, ikea, ring tables

Revision ID: 9f746075ce4c
Revises: 0001_baseline_noop
Create Date: 2026-08-21 01:03:03.995231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f746075ce4c'
down_revision: Union[str, Sequence[str], None] = '0001_baseline_noop'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('current_watts', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kwh_today', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('kwh_7d', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('kwh_30d', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('kwh_mtd', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id')
    )
    op.create_table('ikea_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('ring_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('battery_life', sa.Integer(), nullable=True),
    sa.Column('last_motion_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('energy_circuit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('watts', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['energy_circuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_circuit_logs_circuit_id'), 'energy_circuit_logs', ['circuit_id'], unique=False)
    op.create_table('ikea_device_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('battery_pct', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['ikea_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ikea_device_logs_device_id'), 'ikea_device_logs', ['device_id'], unique=False)
    op.create_table('ring_device_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('battery_life', sa.Integer(), nullable=False),
    sa.Column('last_motion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['ring_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ring_device_logs_device_id'), 'ring_device_logs', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ring_device_logs_device_id'), table_name='ring_device_logs')
    op.drop_table('ring_device_logs')
    op.drop_index(op.f('ix_ikea_device_logs_device_id'), table_name='ikea_device_logs')
    op.drop_table('ikea_device_logs')
    op.drop_index(op.f('ix_energy_circuit_logs_circuit_id'), table_name='energy_circuit_logs')
    op.drop_table('energy_circuit_logs')
    op.drop_table('ring_devices')
    op.drop_table('ikea_devices')
    op.drop_table('energy_circuits')
    # ### end Alembic commands ###
