"""add recorded_at indexes to anemometer, photo_uvmeter, raingauge, energy_circuit, hvac_zone logs

Revision ID: b7c22bb9f561
Revises: e84a030a6faa
Create Date: 2026-08-26 11:49:40.818784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c22bb9f561'
down_revision: Union[str, Sequence[str], None] = 'e84a030a6faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_anemometer_logs_recorded_at'), 'anemometer_logs', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_photo_uvmeter_logs_recorded_at'), 'photo_uvmeter_logs', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_raingauge_logs_recorded_at'), 'raingauge_logs', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_energy_circuit_logs_recorded_at'), 'energy_circuit_logs', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_hvac_zone_logs_recorded_at'), 'hvac_zone_logs', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hvac_zone_logs_recorded_at'), table_name='hvac_zone_logs')
    op.drop_index(op.f('ix_energy_circuit_logs_recorded_at'), table_name='energy_circuit_logs')
    op.drop_index(op.f('ix_raingauge_logs_recorded_at'), table_name='raingauge_logs')
    op.drop_index(op.f('ix_photo_uvmeter_logs_recorded_at'), table_name='photo_uvmeter_logs')
    op.drop_index(op.f('ix_anemometer_logs_recorded_at'), table_name='anemometer_logs')
    # ### end Alembic commands ###
