"""prune hvac_zone_logs to 17 actively-useful fields

Revision ID: e15d91686ce4
Revises: 17afa740f3a0
Create Date: 2026-08-24 17:39:21.963270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15d91686ce4'
down_revision: Union[str, Sequence[str], None] = '17afa740f3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hvac_zone_logs', 'vacation_hold')
    op.drop_column('hvac_zone_logs', 'cool_upper_setpt_limit')
    op.drop_column('hvac_zone_logs', 'cool_lower_setpt_limit')
    op.drop_column('hvac_zone_logs', 'outdoor_temp_status')
    op.drop_column('hvac_zone_logs', 'disp_temperature_status')
    op.drop_column('hvac_zone_logs', 'disp_temperature_available')
    op.drop_column('hvac_zone_logs', 'fan_mode_circulate_allowed')
    op.drop_column('hvac_zone_logs', 'outdoor_humidity_sensor_not_fault')
    op.drop_column('hvac_zone_logs', 'outdoor_humidity_available')
    op.drop_column('hvac_zone_logs', 'outdoor_humidity')
    op.drop_column('hvac_zone_logs', 'heat_lower_setpt_limit')
    op.drop_column('hvac_zone_logs', 'outdoor_temperature_sensor_not_fault')
    op.drop_column('hvac_zone_logs', 'cool_next_period')
    op.drop_column('hvac_zone_logs', 'outdoor_humid_status')
    op.drop_column('hvac_zone_logs', 'fan_mode_on_allowed')
    op.drop_column('hvac_zone_logs', 'switch_auto_allowed')
    op.drop_column('hvac_zone_logs', 'temporary_hold_until_time')
    op.drop_column('hvac_zone_logs', 'fan_mode_auto_allowed')
    op.drop_column('hvac_zone_logs', 'commercial')
    op.drop_column('hvac_zone_logs', 'switch_cool_allowed')
    op.drop_column('hvac_zone_logs', 'indoor_humidity_sensor_not_fault')
    op.drop_column('hvac_zone_logs', 'vacation_hold_until_time')
    op.drop_column('hvac_zone_logs', 'current_setpoint_status')
    op.drop_column('hvac_zone_logs', 'indoor_humidity_sensor_available')
    op.drop_column('hvac_zone_logs', 'outdoor_temperature_available')
    op.drop_column('hvac_zone_logs', 'switch_emergency_heat_allowed')
    op.drop_column('hvac_zone_logs', 'is_in_vacation_hold_mode')
    op.drop_column('hvac_zone_logs', 'heat_next_period')
    op.drop_column('hvac_zone_logs', 'indoor_humid_status')
    op.drop_column('hvac_zone_logs', 'switch_off_allowed')
    op.drop_column('hvac_zone_logs', 'switch_heat_allowed')
    op.drop_column('hvac_zone_logs', 'fan_mode_follow_schedule_allowed')
    op.drop_column('hvac_zone_logs', 'vacation_hold_cancelable')
    op.drop_column('hvac_zone_logs', 'setpoint_change_allowed')
    op.drop_column('hvac_zone_logs', 'heat_upper_setpt_limit')
    op.drop_column('hvac_zone_logs', 'deadband')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hvac_zone_logs', sa.Column('deadband', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('heat_upper_setpt_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('setpoint_change_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('vacation_hold_cancelable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('fan_mode_follow_schedule_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('switch_heat_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('switch_off_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('indoor_humid_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('heat_next_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('is_in_vacation_hold_mode', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('switch_emergency_heat_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('outdoor_temperature_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('indoor_humidity_sensor_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('current_setpoint_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('vacation_hold_until_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('indoor_humidity_sensor_not_fault', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('switch_cool_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('commercial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('fan_mode_auto_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('temporary_hold_until_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('switch_auto_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('fan_mode_on_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('outdoor_humid_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('cool_next_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('outdoor_temperature_sensor_not_fault', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('heat_lower_setpt_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('outdoor_humidity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('outdoor_humidity_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('outdoor_humidity_sensor_not_fault', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('fan_mode_circulate_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('disp_temperature_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('disp_temperature_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('outdoor_temp_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('cool_lower_setpt_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('cool_upper_setpt_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hvac_zone_logs', sa.Column('vacation_hold', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
