"""add battery_ok and anemometer/photo-uvmeter/raingauge tables

Revision ID: e84a030a6faa
Revises: 51de07cbc136
Create Date: 2026-08-25 14:52:33.608624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e84a030a6faa'
down_revision: Union[str, Sequence[str], None] = '51de07cbc136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anemometers',
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('current_speed_mph', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('current_direction_deg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('photo_uvmeters',
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('current_lumens', sa.Integer(), nullable=True),
    sa.Column('current_uv_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('raingauges',
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('current_rain_in', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('anemometer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anemometer_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('speed_mph', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('direction_deg', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anemometer_id'], ['anemometers.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anemometer_logs_anemometer_id'), 'anemometer_logs', ['anemometer_id'], unique=False)
    op.create_table('photo_uvmeter_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_uvmeter_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('lumens', sa.Integer(), nullable=False),
    sa.Column('uv_index', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_uvmeter_id'], ['photo_uvmeters.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_uvmeter_logs_photo_uvmeter_id'), 'photo_uvmeter_logs', ['photo_uvmeter_id'], unique=False)
    op.create_table('raingauge_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raingauge_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rain_in', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raingauge_id'], ['raingauges.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raingauge_logs_raingauge_id'), 'raingauge_logs', ['raingauge_id'], unique=False)
    op.add_column('tstats_thermohygrometer', sa.Column('battery_ok', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tstats_thermohygrometer', 'battery_ok')
    op.drop_index(op.f('ix_raingauge_logs_raingauge_id'), table_name='raingauge_logs')
    op.drop_table('raingauge_logs')
    op.drop_index(op.f('ix_photo_uvmeter_logs_photo_uvmeter_id'), table_name='photo_uvmeter_logs')
    op.drop_table('photo_uvmeter_logs')
    op.drop_index(op.f('ix_anemometer_logs_anemometer_id'), table_name='anemometer_logs')
    op.drop_table('anemometer_logs')
    op.drop_table('raingauges')
    op.drop_table('photo_uvmeters')
    op.drop_table('anemometers')
    # ### end Alembic commands ###
