"""add hvac zone tables

Revision ID: ecf1fdc29e9a
Revises: 9f746075ce4c
Create Date: 2026-08-24 12:36:00.550186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecf1fdc29e9a'
down_revision: Union[str, Sequence[str], None] = '9f746075ce4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hvac_zones',
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('hvac_zone_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hvac_zone_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disp_temperature', sa.Integer(), nullable=True),
    sa.Column('heat_setpoint', sa.Integer(), nullable=True),
    sa.Column('cool_setpoint', sa.Integer(), nullable=True),
    sa.Column('display_units', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('status_heat', sa.Integer(), nullable=True),
    sa.Column('status_cool', sa.Integer(), nullable=True),
    sa.Column('hold_until_capable', sa.Boolean(), nullable=True),
    sa.Column('schedule_capable', sa.Boolean(), nullable=True),
    sa.Column('vacation_hold', sa.Integer(), nullable=True),
    sa.Column('dual_setpoint_status', sa.Boolean(), nullable=True),
    sa.Column('heat_next_period', sa.Integer(), nullable=True),
    sa.Column('cool_next_period', sa.Integer(), nullable=True),
    sa.Column('heat_lower_setpt_limit', sa.Integer(), nullable=True),
    sa.Column('heat_upper_setpt_limit', sa.Integer(), nullable=True),
    sa.Column('cool_lower_setpt_limit', sa.Integer(), nullable=True),
    sa.Column('cool_upper_setpt_limit', sa.Integer(), nullable=True),
    sa.Column('schedule_heat_sp', sa.Integer(), nullable=True),
    sa.Column('schedule_cool_sp', sa.Integer(), nullable=True),
    sa.Column('switch_auto_allowed', sa.Boolean(), nullable=True),
    sa.Column('switch_cool_allowed', sa.Boolean(), nullable=True),
    sa.Column('switch_off_allowed', sa.Boolean(), nullable=True),
    sa.Column('switch_heat_allowed', sa.Boolean(), nullable=True),
    sa.Column('switch_emergency_heat_allowed', sa.Boolean(), nullable=True),
    sa.Column('system_switch_position', sa.Integer(), nullable=True),
    sa.Column('deadband', sa.Integer(), nullable=True),
    sa.Column('indoor_humidity', sa.Integer(), nullable=True),
    sa.Column('commercial', sa.Boolean(), nullable=True),
    sa.Column('disp_temperature_available', sa.Boolean(), nullable=True),
    sa.Column('indoor_humidity_sensor_available', sa.Boolean(), nullable=True),
    sa.Column('indoor_humidity_sensor_not_fault', sa.Boolean(), nullable=True),
    sa.Column('vacation_hold_until_time', sa.Integer(), nullable=True),
    sa.Column('temporary_hold_until_time', sa.Integer(), nullable=True),
    sa.Column('is_in_vacation_hold_mode', sa.Boolean(), nullable=True),
    sa.Column('vacation_hold_cancelable', sa.Boolean(), nullable=True),
    sa.Column('setpoint_change_allowed', sa.Boolean(), nullable=True),
    sa.Column('outdoor_temperature', sa.Integer(), nullable=True),
    sa.Column('outdoor_humidity', sa.Integer(), nullable=True),
    sa.Column('outdoor_humidity_available', sa.Boolean(), nullable=True),
    sa.Column('outdoor_temperature_available', sa.Boolean(), nullable=True),
    sa.Column('disp_temperature_status', sa.Integer(), nullable=True),
    sa.Column('indoor_humid_status', sa.Integer(), nullable=True),
    sa.Column('outdoor_temp_status', sa.Integer(), nullable=True),
    sa.Column('outdoor_humid_status', sa.Integer(), nullable=True),
    sa.Column('outdoor_temperature_sensor_not_fault', sa.Boolean(), nullable=True),
    sa.Column('outdoor_humidity_sensor_not_fault', sa.Boolean(), nullable=True),
    sa.Column('current_setpoint_status', sa.Integer(), nullable=True),
    sa.Column('equipment_output_status', sa.Integer(), nullable=True),
    sa.Column('fan_mode', sa.Integer(), nullable=True),
    sa.Column('fan_mode_auto_allowed', sa.Boolean(), nullable=True),
    sa.Column('fan_mode_on_allowed', sa.Boolean(), nullable=True),
    sa.Column('fan_mode_circulate_allowed', sa.Boolean(), nullable=True),
    sa.Column('fan_mode_follow_schedule_allowed', sa.Boolean(), nullable=True),
    sa.Column('fan_is_running', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hvac_zone_id'], ['hvac_zones.external_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hvac_zone_logs_hvac_zone_id'), 'hvac_zone_logs', ['hvac_zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hvac_zone_logs_hvac_zone_id'), table_name='hvac_zone_logs')
    op.drop_table('hvac_zone_logs')
    op.drop_table('hvac_zones')
    # ### end Alembic commands ###
